name: PurpleDuck
favicon: null
layout_spectrum: 0.5191920134238899
typography_spectrum: 0.259243541629985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08320074086077511
  lightness: 0.21993025578558445
  saturation: 0.7113881481345743
  rhythmicContrast: 0.10814926913008094
purpose: []
